apiVersion: v1
kind: Service
metadata:
  name: {{ include "agnos-worker.fullname" . }}
  labels:
    {{- include "agnos-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agnos-worker.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP